---
title: "AD Code"
Author: "Muhammad Elsadany"
---


```{r}
# load libraries
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(DESeq2)
library(pheatmap)
library(boxplotdbl)
library(gplots)
```



#Data retrieval part
```{r}
ADData <- read.csv("data/AD_Counts_2.csv", header=T, check.names=FALSE, row.names=1)
ADmeta <- read.csv("data/AD_Meta_2.csv", header=T, check.names = FALSE,  row.names=1)
```


#Check step
```{r}

### Check that sample names match in both files
all(colnames(ADData) %in% rownames(ADmeta))
all(colnames(ADData) == rownames(ADmeta))

```



#DESeq Object for comparing AD VS. Old
```{r}
## Create DESeq2Dataset object
ADdds <- DESeqDataSetFromMatrix(countData = ADData, colData = ADmeta, design = ~ SampleType2)
#View(counts(ADdds))
## Run analysis
ADdds <- DESeq(ADdds)
```



```{r}
print(ADdds)

```



#generating normalized counts
```{r}
ADdds2 <- estimateSizeFactors(ADdds)
ADnormalized_counts <- counts(ADdds2, normalized=TRUE)
write.csv(ADnormalized_counts, file="data/ADnormalized_counts.csv")

```


#contrast
```{r}
## Define contrasts, extract results table, and shrink the log2 fold changes

#Define your disease group first, then your control 

contrast_ <- c("SampleType2", "AD", "Old")
resultsNames(ADdds)


res_table_unshrunken <- results(ADdds, contrast=contrast_, alpha = 0.05, lfcThreshold = 0)

res_table_shrunken <- lfcShrink(ADdds, contrast=contrast_, res=res_table_unshrunken, type="ashr")

```


# summary function

```{r}
## Summarize results
summary(res_table_unshrunken)

```

#saving results table
```{r}
res_table_unshrunken <- res_table_unshrunken %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
write.csv(res_table_unshrunken, file="results/AD_VS._Old_res_table_unshrunken_withoutlfcThreshold.csv")



res_table_shrunken <- res_table_shrunken %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
write.csv(res_table_shrunken, file="results/AD_VS._Old_res_table_shrunken_withoutlfcThreshold.csv")

```





#setting thresholds for DEGs
```{r}
### Set thresholds
padj.cutoff <- 0.05
lfc.cutoff <- 0

```


#subsetting table for DEGs values only
```{r}
sigOE <- res_table_unshrunken %>%
        filter(padj < padj.cutoff & abs(log2FoldChange) > lfc.cutoff)

write.csv(sigOE, file="results/AD_VS._Old_DEGslfc0.csv")
```











#creating tibble objects 
```{r}
# Create tibbles including row names
AD_meta <- ADmeta %>% 
  rownames_to_column(var="samplename") %>% 
  as_tibble()
        
ADnormalized_counts <- ADnormalized_counts %>% 
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

```






#mutating res_table with threshold
```{r}
## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 0 in either direction

res_table_shrunken_2 <- res_table_shrunken %>% 
                  mutate(threshold_OE = abs(log2FoldChange) > 0)

```

#volcano plot
```{r}
## Volcano plot
jpeg(file="results/AD_VS._Old_Volcano_plot.png")
ggplot(res_table_shrunken_2) +
        geom_point(aes(x = log2FoldChange, y = -log10(padj), colour = threshold_OE)) +
        ggtitle("AD VS. Old") +
        xlab("log2 fold change") + 
        ylab("-log10 adjusted p-value") +
        #scale_y_continuous(limits = c(0,50)) +
        theme(legend.position = "none",
              plot.title = element_text(size = rel(1.5), hjust = 0.5),
              axis.title = element_text(size = rel(1.25)))  


```







#heatmap for DEGs
```{r}
### Annotate our heatmap (optional)
annotation2 <- AD_meta %>% 
	dplyr::select(samplename, SampleType2) %>%
  mutate(SampleType = ifelse(SampleType2 == "Old", "Control", "AD")) %>%
  arrange(desc(SampleType)) %>%
  select(samplename, SampleType) %>%
  column_to_rownames("samplename")
# levels(annotation2) <- unique(annotation2$SampleType2)

# annot_colors <- list(SampleTyp2=c(AD="#FF9189",Old="#00DBE4"))
annot_colors <- c("#00DBE4", "#FF9189")
names(annot_colors) <- unique(annotation2$SampleType)
annot_colors <- list(SampleType = annot_colors)

vsd <- vst(ADdds)
### Set a color palette
heat_colors2 <- brewer.pal(4, "YlOrRd")

genes <- sigOE$gene

### Run pheatmap
svg(filename ="results/AD_VS._Old_DEGsHeatMaplfc0_MS_100922.svg")
tiff(filename = "results/AD_VS._Old_DEGsHeatMaplfc0_MS_100922.tiff", width = 2100, height = 1500, res = 300)
pheatmap(assay(vsd)[genes, rownames(annotation2)],
         color = heat_colors2, 
         cluster_rows = T,
         cluster_cols = F,
         show_rownames = F,
         annotation_col = annotation2,
         annotation_colors = annot_colors,
         annotation_names_col = F,
         border_color = NA,
         fontsize = 10,
         scale = "row", show_rownames = F, show_colnames = F,
         
         fontsize_row = 6,
         height = 400)
dev.off()

```


















